import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import SessionWrapper from '@/components/SessionWrapper/SessionWrapper';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Inter({
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className="bg-bg-color">
          <main className={`${inter.className} my-0 mx-auto  max-w-5xl`}>
            {children}
          </main>
        </body>
      </html>
    </SessionWrapper>
  );
}
